version: '3'

services:

  database:
    build: './database'
    environment:
      - 'POSTGRES_PASSWORD=database'

  app:
    build: './app'
    volumes:
      - './app:/app'
      - './data:/data'
    ports:
      - '2200:80'
